import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main sidebar for overview and quick start
  mainSidebar: [
    {
      type: 'category',
      label: 'Overview',
      items: [
        'overview/about',
        'overview/architecture',
        'overview/changelog',
      ],
    },
    {
      type: 'category',
      label: 'Quick Start',
      items: [
        'quick-start/developers',
        'quick-start/merchants',
      ],
    },
    {
      type: 'category',
      label: 'Glossary & Resources',
      items: [
        'glossary/index',
        'resources/index',
      ],
    },
  ],

  // Developer-focused sidebar
  developerSidebar: [
    {
      type: 'category',
      label: 'Developers',
      items: [
        {type: 'doc', id: 'developers/index', label: 'Developer Home'},
        {
          type: 'category',
          label: 'Getting Started',
          items: [
            {type: 'doc', id: 'developers/getting-started/index', label: 'Quickstart'},
            {type: 'doc', id: 'developers/getting-started/authentication', label: 'Authentication'},
            {type: 'doc', id: 'developers/getting-started/api-fundamentals', label: 'API Fundamentals'},
            {type: 'doc', id: 'developers/getting-started/sandbox', label: 'Sandbox & Test Cards'},
          ],
        },
        {
          type: 'category',
          label: 'Payments',
          items: [
            {type: 'doc', id: 'developers/payments/index', label: 'Overview'},
            {type: 'doc', id: 'developers/payments/checkout-api', label: 'Checkout API'},
            {type: 'doc', id: 'developers/payments/payment-methods', label: 'Payment Methods'},
            {type: 'doc', id: 'developers/payments/native-payments', label: 'Native Payments'},
            {type: 'doc', id: 'developers/payments/checkout-sdk', label: 'Checkout SDK'},
          ],
        },
        {type: 'doc', id: 'developers/operations', label: 'Operations'},
        {
          type: 'category',
          label: 'Cards & Tokenization',
          items: [
            {type: 'doc', id: 'developers/cards-and-tokens/index', label: 'Overview'},
            {type: 'doc', id: 'developers/cards-and-tokens/user-cards', label: 'User Cards'},
            {type: 'doc', id: 'developers/cards-and-tokens/recurring-payments', label: 'Recurring Payments'},
          ],
        },
        {type: 'doc', id: 'developers/invoices', label: 'Invoices'},
        {
          type: 'category',
          label: 'Webhooks & Events',
          items: [
            {type: 'doc', id: 'developers/webhooks/index', label: 'Overview & Setup'},
            {type: 'doc', id: 'developers/webhooks/payment-events', label: 'Payment Events'},
            {type: 'doc', id: 'developers/webhooks/operation-events', label: 'Operation Events'},
            {type: 'doc', id: 'developers/webhooks/verify-signatures', label: 'Verify Signatures'},
          ],
        },
        {type: 'doc', id: 'developers/notifications', label: 'Notifications'},
        {type: 'doc', id: 'developers/reports', label: 'Reports'},
        {
          type: 'category',
          label: 'Reference',
          items: [
            {type: 'doc', id: 'developers/reference/error-codes', label: 'Error Codes'},
            {type: 'doc', id: 'developers/reference/payment-states', label: 'Payment States'},
            {type: 'doc', id: 'developers/reference/glossary', label: 'Glossary'},
          ],
        },
        {
          type: 'category',
          label: 'API Reference',
          items: [{type: 'autogenerated', dirName: 'developers/apis'}],
        },
      ],
    },
  ],

  // Business user-focused sidebar
  businessSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'business/dashboard-tour',
      ],
    },
  ],

};

export default sidebars;
