/**
 * Generic schema renderer for embedding OpenAPI schemas in documentation pages.
 *
 * Usage in MDX:
 *   import SchemaEmbed from "@site/src/components/SchemaEmbed";
 *   <SchemaEmbed path="SchemaWebhook.json" />
 *   <SchemaEmbed path="SchemaWebhook.json" parentSchemaName="payment-webhook" />
 *
 * The schema JSON must be pre-generated by scripts/extract-schema.ts
 * and placed in static/schemas/.
 */

import React from "react";
import SchemaNode from "@site/src/theme/Schema";

interface SchemaEmbedProps {
  /** Path to the schema JSON file relative to static/schemas/ */
  path: string;
  /** Schema type for filtering readOnly/writeOnly fields. Default: "response" */
  schemaType?: "request" | "response";
  /** Parent name for fragment ID generation. Default: derived from filename */
  parentSchemaName?: string;
}

export default function SchemaEmbed({
  path,
  schemaType = "response",
  parentSchemaName,
}: SchemaEmbedProps): React.JSX.Element {
  // Derive parent name from filename if not provided
  // e.g., "SchemaWebhook.json" → "SchemaWebhook"
  const derivedName =
    parentSchemaName || path.replace(/\.json$/, "").replace(/[^a-zA-Z0-9]/g, "-");

  // Static import — the schema JSON is resolved at build time by webpack
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const schema = require(`@site/static/schemas/${path}`);

  return (
    <div className={schemaType === "response" ? "schema-embed-response" : undefined}>
      <SchemaNode
        schema={schema}
        schemaType={schemaType}
        parentSchemaName={derivedName}
      />
    </div>
  );
}
