import React from "react";
import Diagram from "@site/src/components/Diagram";

/**
 * AutoPay subscription flow: one checkout call, then AutoPay owns everything after.
 *
 * Single inline, theme-aware SVG generated by the `svg-diagram` skill
 * (scripts/inline-svg.py, slug "autopay-flow"). Scoped `<style>` with light rules
 * + `[data-theme='dark']` overrides; renders in true Poppins and switches with
 * the page theme. To change it, edit the source SVG and re-run inline-svg.py.
 *
 * Accuracy notes (per the page's Step-by-Step / Use Cases):
 *  - Subscription creation is SYNCHRONOUS: Ottu Connect commits the checkout
 *    transaction, then calls AutoPay before returning the 201 response — this is
 *    a direct call, not a webhook, so the arrow is solid, not dashed.
 *  - AutoPay never touches cardholder data. The CIT charge is processed by Ottu
 *    Connect; the Checkout Page sits OUTSIDE the Ottu Platform box (same
 *    convention as RecurringFlow) because it may be Ottu-hosted or a
 *    self-hosted SDK embed.
 *  - After the CIT settles, ownership of billing cycles, retries, dunning, and
 *    the customer self-service page moves to AutoPay — the merchant makes no
 *    further calls to keep the subscription running.
 */
const SVG = String.raw`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 960 460" role="img" aria-labelledby="ap-title-autopay-flow ap-desc-autopay-flow" preserveAspectRatio="xMidYMid meet" class="ottu-dgm--autopay-flow">
  <title id="ap-title-autopay-flow">AutoPay subscription flow</title>
  <desc id="ap-desc-autopay-flow">The merchant makes one Checkout API call with payment_type auto_pay. Ottu Connect commits the transaction and calls AutoPay synchronously, which creates the subscription. The merchant redirects the customer to the checkout page, where the customer enters their card and pays the first charge, the CIT. From then on, AutoPay owns the billing cycles, retries, dunning, and the customer self-service page — the merchant makes no further calls to keep the subscription running.</desc>

  <defs>
    <marker id="arrow-autopay-flow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto">
      <path class="arrow-head" d="M0,1 L9,5 L0,9 z" />
    </marker>
    <style>
      .ottu-dgm--autopay-flow .node { fill: #FFFFFF; stroke: #D4D4D4; stroke-width: 1.4; }
      .ottu-dgm--autopay-flow .accent { fill: #0B82BE; stroke: #0B82BE; stroke-width: 1.4; }
      .ottu-dgm--autopay-flow .container-bg { fill: #F6FAFD; stroke: #0B82BE; stroke-dasharray: 5 5; stroke-width: 1.2; opacity: 0.85; }
      .ottu-dgm--autopay-flow .platform-label { fill: #0B82BE; font: 700 10px 'Poppins', system-ui, -apple-system, sans-serif; letter-spacing: 1.6px; }
      .ottu-dgm--autopay-flow .label { fill: #302F37; font: 600 13px 'Poppins', system-ui, -apple-system, sans-serif; }
      .ottu-dgm--autopay-flow .label-white { fill: #FFFFFF; font: 600 13px 'Poppins', system-ui, -apple-system, sans-serif; }
      .ottu-dgm--autopay-flow .sub { fill: #6B6B72; font: 400 11px 'Poppins', system-ui, -apple-system, sans-serif; }
      .ottu-dgm--autopay-flow .sub-white { fill: #FFFFFF; font: 400 11px 'Poppins', system-ui, -apple-system, sans-serif; opacity: 0.9; }
      .ottu-dgm--autopay-flow .arrow { fill: none; stroke: #8B8A90; stroke-width: 1.4; }
      .ottu-dgm--autopay-flow .arrow-head { fill: #8B8A90; }
      .ottu-dgm--autopay-flow .arrow-label { fill: #6B6B72; font: 500 10px 'Poppins', system-ui, -apple-system, sans-serif; letter-spacing: 0.3px; }
      .ottu-dgm--autopay-flow .arrow-label-bg { fill: #F6FAFD; }

      /* dark theme — overrides only what changes */
      [data-theme='dark'] .ottu-dgm--autopay-flow .node { fill: #171A21; stroke: #1E2939; }
      [data-theme='dark'] .ottu-dgm--autopay-flow .container-bg { fill: #0F1A22; }
      [data-theme='dark'] .ottu-dgm--autopay-flow .platform-label { fill: #5CB4E1; }
      [data-theme='dark'] .ottu-dgm--autopay-flow .label { fill: #E5E7EB; }
      [data-theme='dark'] .ottu-dgm--autopay-flow .sub { fill: #A0A0A8; }
      [data-theme='dark'] .ottu-dgm--autopay-flow .arrow { stroke: #8A8A92; }
      [data-theme='dark'] .ottu-dgm--autopay-flow .arrow-head { fill: #8A8A92; }
      [data-theme='dark'] .ottu-dgm--autopay-flow .arrow-label { fill: #A0A0A8; }
      [data-theme='dark'] .ottu-dgm--autopay-flow .arrow-label-bg { fill: #0F1A22; }
    </style>
  </defs>

  <!-- Ottu Platform container -->
  <rect class="container-bg" x="300" y="110" width="620" height="300" rx="14" />
  <text class="platform-label" x="320" y="136">OTTU PLATFORM</text>

  <!-- Customer -->
  <rect class="node" x="30" y="30" width="180" height="48" rx="24" />
  <text class="label" x="120" y="59" text-anchor="middle">Customer</text>

  <!-- Merchant Backend -->
  <rect class="node" x="30" y="130" width="200" height="76" rx="8" />
  <text class="label" x="130" y="162" text-anchor="middle">Merchant Backend</text>
  <text class="sub" x="130" y="184" text-anchor="middle">Your server</text>

  <!-- Checkout Page (OUTSIDE platform: Ottu-hosted or self-hosted SDK embed) -->
  <rect class="node" x="700" y="20" width="220" height="60" rx="8" />
  <text class="label" x="810" y="46" text-anchor="middle">Checkout Page</text>
  <text class="sub" x="810" y="66" text-anchor="middle">Ottu-hosted or SDK embed</text>

  <!-- Ottu Connect (accent) -->
  <rect class="accent" x="330" y="160" width="220" height="76" rx="8" />
  <text class="label-white" x="440" y="192" text-anchor="middle">Ottu Connect</text>
  <text class="sub-white" x="440" y="214" text-anchor="middle">Commits the transaction</text>

  <!-- AutoPay (accent) -->
  <rect class="accent" x="330" y="280" width="220" height="76" rx="8" />
  <text class="label-white" x="440" y="312" text-anchor="middle">AutoPay</text>
  <text class="sub-white" x="440" y="334" text-anchor="middle">Creates the subscription</text>

  <!-- Ongoing ownership -->
  <rect class="node" x="610" y="230" width="290" height="150" rx="8" />
  <text class="label" x="755" y="264" text-anchor="middle">Owned by AutoPay</text>
  <text class="sub" x="755" y="286" text-anchor="middle">Billing cycles · retries</text>
  <text class="sub" x="755" y="306" text-anchor="middle">Dunning · notifications</text>
  <text class="sub" x="755" y="326" text-anchor="middle">Customer self-service page</text>

  <!-- Arrows -->
  <path class="arrow" d="M 230 168 C 270 168 300 190 330 198" marker-end="url(#arrow-autopay-flow)" />
  <rect class="arrow-label-bg" x="236" y="150" width="130" height="14" rx="3" />
  <text class="arrow-label" x="301" y="161" text-anchor="middle">checkout call · auto_pay</text>

  <path class="arrow" d="M 440 236 L 440 280" marker-end="url(#arrow-autopay-flow)" />
  <rect class="arrow-label-bg" x="450" y="251" width="150" height="14" rx="3" />
  <text class="arrow-label" x="525" y="262" text-anchor="middle">creates subscription · sync</text>

  <path class="arrow" d="M 130 130 L 120 78" marker-end="url(#arrow-autopay-flow)" />
  <rect class="arrow-label-bg" x="58" y="96" width="124" height="14" rx="3" />
  <text class="arrow-label" x="120" y="107" text-anchor="middle">redirect to checkout</text>

  <path class="arrow" d="M 210 48 C 400 12 570 12 700 46" marker-end="url(#arrow-autopay-flow)" />
  <rect class="arrow-label-bg" x="380" y="10" width="150" height="14" rx="3" />
  <text class="arrow-label" x="455" y="21" text-anchor="middle">enters card · pays (CIT)</text>

  <path class="arrow" d="M 760 80 C 740 115 620 145 552 172" marker-end="url(#arrow-autopay-flow)" />
  <rect class="arrow-label-bg" x="650" y="116" width="110" height="14" rx="3" />
  <text class="arrow-label" x="705" y="127" text-anchor="middle">submits payment</text>

  <path class="arrow" d="M 550 300 L 608 270" marker-end="url(#arrow-autopay-flow)" />
  <rect class="arrow-label-bg" x="560" y="248" width="90" height="14" rx="3" />
  <text class="arrow-label" x="605" y="259" text-anchor="middle">ongoing</text>
</svg>`;

export default function AutoPayFlowDiagram(): React.JSX.Element {
  return (
    <Diagram
      svg={SVG}
      alt="AutoPay subscription flow: the merchant makes one Checkout API call with payment_type auto_pay; Ottu Connect commits the transaction and calls AutoPay synchronously, which creates the subscription; the merchant redirects the customer to the checkout page to pay the first charge (the CIT); from then on AutoPay owns the billing cycles, retries, dunning, and the customer self-service page."
    />
  );
}
