import React from "react";
import Diagram from "@site/src/components/Diagram";

/**
 * Loyalty earn flow: opt in on the Checkout API call, reward issued once the payment is paid.
 *
 * Single inline, theme-aware SVG generated by the `svg-diagram` skill
 * (scripts/inline-svg.py, slug "loyalty-earn-flow"). Scoped `<style>` with light rules
 * + `[data-theme='dark']` overrides; renders in true Poppins and switches with
 * the page theme. To change it, edit the source SVG and re-run inline-svg.py.
 *
 * PUBLIC SURFACE: this diagram, its <title>/<desc> and the alt text below all
 * ship to merchants. Describe only what a merchant calls and sees; do not
 * expose Ottu's internal service topology.
 */
const SVG = String.raw`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 960 400" role="img" aria-labelledby="diagram-title-loyalty-earn-flow diagram-desc-loyalty-earn-flow" preserveAspectRatio="xMidYMid meet" class="ottu-dgm--loyalty-earn-flow">
  <title id="diagram-title-loyalty-earn-flow">Loyalty earn flow</title>
  <desc id="diagram-desc-loyalty-earn-flow">The merchant creates a Checkout API session with the loyalty flag and the customer's phone number. The customer pays through a payment gateway. When the transaction reaches paid, Ottu issues the reward to the customer's loyalty account at the loyalty provider, such as STC Qitaf.</desc>
  <defs>
    <marker id="arrow-loyalty-earn-flow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path class="arrow-head" d="M0,1 L9,5 L0,9 z" /></marker>
    <style>
      .ottu-dgm--loyalty-earn-flow .node { fill: #FFFFFF; stroke: #D4D4D4; stroke-width: 1.4; }
      .ottu-dgm--loyalty-earn-flow .accent { fill: #0B82BE; stroke: #0B82BE; stroke-width: 1.4; }
      .ottu-dgm--loyalty-earn-flow .container-bg { fill: #F6FAFD; stroke: #0B82BE; stroke-dasharray: 5 5; stroke-width: 1.2; opacity: 0.85; }
      .ottu-dgm--loyalty-earn-flow .platform-label { fill: #0B82BE; font: 700 10px 'Poppins', system-ui, -apple-system, sans-serif; letter-spacing: 1.6px; }
      .ottu-dgm--loyalty-earn-flow .label { fill: #302F37; font: 600 13px 'Poppins', system-ui, -apple-system, sans-serif; }
      .ottu-dgm--loyalty-earn-flow .label-white { fill: #FFFFFF; font: 600 13px 'Poppins', system-ui, -apple-system, sans-serif; }
      .ottu-dgm--loyalty-earn-flow .sub { fill: #6B6B72; font: 400 11px 'Poppins', system-ui, -apple-system, sans-serif; }
      .ottu-dgm--loyalty-earn-flow .sub-white { fill: #FFFFFF; font: 400 11px 'Poppins', system-ui, -apple-system, sans-serif; opacity: 0.9; }
      .ottu-dgm--loyalty-earn-flow .divider { stroke: #E0E0E3; stroke-width: 1; }
      .ottu-dgm--loyalty-earn-flow .arrow { fill: none; stroke: #8B8A90; stroke-width: 1.4; }
      .ottu-dgm--loyalty-earn-flow .arrow-head { fill: #8B8A90; }
      .ottu-dgm--loyalty-earn-flow .arrow-label { fill: #6B6B72; font: 500 10px 'Poppins', system-ui, -apple-system, sans-serif; letter-spacing: 0.3px; }
      .ottu-dgm--loyalty-earn-flow .arrow-label-bg { fill: #FFFFFF; }
    

      /* dark theme — overrides only what changes */
      [data-theme='dark'] .ottu-dgm--loyalty-earn-flow .node { fill: #171A21; stroke: #1E2939; }
      [data-theme='dark'] .ottu-dgm--loyalty-earn-flow .container-bg { fill: #0F1A22; }
      [data-theme='dark'] .ottu-dgm--loyalty-earn-flow .platform-label { fill: #5CB4E1; }
      [data-theme='dark'] .ottu-dgm--loyalty-earn-flow .label { fill: #E5E7EB; }
      [data-theme='dark'] .ottu-dgm--loyalty-earn-flow .sub { fill: #A0A0A8; }
      [data-theme='dark'] .ottu-dgm--loyalty-earn-flow .divider { stroke: #1E2939; }
      [data-theme='dark'] .ottu-dgm--loyalty-earn-flow .arrow { stroke: #8A8A92; }
      [data-theme='dark'] .ottu-dgm--loyalty-earn-flow .arrow-head { fill: #8A8A92; }
      [data-theme='dark'] .ottu-dgm--loyalty-earn-flow .arrow-label { fill: #A0A0A8; }
      [data-theme='dark'] .ottu-dgm--loyalty-earn-flow .arrow-label-bg { fill: #0F1A22; }
    </style>
  </defs>
  <rect class="container-bg" x="300" y="50" width="280" height="300" rx="14" />
  <text class="platform-label" x="320" y="76">OTTU PLATFORM</text>
  <rect class="node" x="30" y="100" width="200" height="64" rx="8" />
  <text class="label" x="130" y="129" text-anchor="middle">Merchant Backend</text>
  <text class="sub" x="130" y="147" text-anchor="middle">Your server</text>
  <rect class="node" x="30" y="250" width="200" height="64" rx="8" />
  <text class="label" x="130" y="279" text-anchor="middle">Customer</text>
  <text class="sub" x="130" y="297" text-anchor="middle">Pays at checkout</text>
  <rect class="node" x="330" y="100" width="220" height="64" rx="8" />
  <text class="label" x="440" y="129" text-anchor="middle">Checkout API</text>
  <text class="sub" x="440" y="147" text-anchor="middle">Stores your loyalty intent</text>
  <rect class="accent" x="330" y="250" width="220" height="64" rx="8" />
  <text class="label-white" x="440" y="279" text-anchor="middle">Loyalty reward</text>
  <text class="sub-white" x="440" y="297" text-anchor="middle">Issued once paid</text>
  <rect class="node" x="720" y="100" width="200" height="64" rx="8" />
  <text class="label" x="820" y="129" text-anchor="middle">Payment gateway</text>
  <text class="sub" x="820" y="147" text-anchor="middle">Settles the payment</text>
  <rect class="node" x="720" y="250" width="200" height="64" rx="8" />
  <text class="label" x="820" y="279" text-anchor="middle">Loyalty provider</text>
  <text class="sub" x="820" y="297" text-anchor="middle">e.g. STC Qitaf</text>
  <path class="arrow" d="M 230 124 L 330 124" marker-end="url(#arrow-loyalty-earn-flow)" />
  <rect class="arrow-label-bg" x="249" y="105" width="63" height="16" rx="3" />
  <text class="arrow-label" x="280" y="116" text-anchor="middle">1 create</text>
  <path class="arrow" d="M 230 282 L 280 282 L 280 150 L 330 150" marker-end="url(#arrow-loyalty-earn-flow)" />
  <rect class="arrow-label-bg" x="255" y="227" width="51" height="16" rx="3" />
  <text class="arrow-label" x="280" y="238" text-anchor="middle">2 pays</text>
  <path class="arrow" d="M 550 132 L 720 132" marker-end="url(#arrow-loyalty-earn-flow)" />
  <rect class="arrow-label-bg" x="566" y="113" width="139" height="16" rx="3" />
  <text class="arrow-label" x="635" y="124" text-anchor="middle">customer pays through</text>
  <path class="arrow" d="M 440 164 L 440 250" marker-end="url(#arrow-loyalty-earn-flow)" />
  <rect class="arrow-label-bg" x="391" y="198" width="98" height="16" rx="3" />
  <text class="arrow-label" x="440" y="209" text-anchor="middle">3 reaches paid</text>
  <path class="arrow" d="M 550 282 L 720 282" marker-end="url(#arrow-loyalty-earn-flow)" />
  <rect class="arrow-label-bg" x="586" y="263" width="98" height="16" rx="3" />
  <text class="arrow-label" x="635" y="274" text-anchor="middle">4 issue points</text>
</svg>`;

export default function LoyaltyFlowDiagram(): React.JSX.Element {
  return (
    <Diagram
      svg={SVG}
      alt="The merchant creates a Checkout API session with the loyalty flag and the customer's phone number; the customer pays; when the transaction reaches paid, Ottu issues the reward to the customer's account at the loyalty provider."
    />
  );
}
