import React from "react";
import Diagram from "@site/src/components/Diagram";

/**
 * Refund of an order paid with redeemed points: gateway first, points second, both in one request.
 *
 * Single inline, theme-aware SVG generated by the `svg-diagram` skill
 * (scripts/inline-svg.py, slug "loyalty-refund-flow"). Scoped `<style>` with light rules
 * + `[data-theme='dark']` overrides; renders in true Poppins and switches with
 * the page theme. To change it, edit the source SVG and re-run inline-svg.py.
 *
 * PUBLIC SURFACE: this diagram, its <title>/<desc> and the alt text below all
 * ship to merchants. Describe only what a merchant calls and sees; do not
 * expose Ottu's internal service topology.
 */
const SVG = String.raw`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 960 600" role="img" aria-labelledby="diagram-title-loyalty-refund-flow diagram-desc-loyalty-refund-flow" preserveAspectRatio="xMidYMid meet" class="ottu-dgm--loyalty-refund-flow">
  <title id="diagram-title-loyalty-refund-flow">Refunding an order paid with points</title>
  <desc id="diagram-desc-loyalty-refund-flow">The merchant refunds the gateway portion of a split order through Ottu. Ottu refunds the payment gateway, then reverses the redeemed points at STC Qitaf, then answers the merchant with both records booked. Two operation webhooks follow, the points return first, and Ottu finally reduces the earned reward.</desc>
  <defs>
    <marker id="arrow-loyalty-refund-flow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path class="arrow-head" d="M0,1 L9,5 L0,9 z" /></marker>
    <style>
      .ottu-dgm--loyalty-refund-flow .node { fill: #FFFFFF; stroke: #D4D4D4; stroke-width: 1.4; }
      .ottu-dgm--loyalty-refund-flow .accent { fill: #0B82BE; stroke: #0B82BE; stroke-width: 1.4; }
      .ottu-dgm--loyalty-refund-flow .container-bg { fill: #F6FAFD; stroke: #0B82BE; stroke-dasharray: 5 5; stroke-width: 1.2; opacity: 0.85; }
      .ottu-dgm--loyalty-refund-flow .platform-label { fill: #0B82BE; font: 700 10px 'Poppins', system-ui, -apple-system, sans-serif; letter-spacing: 1.6px; }
      .ottu-dgm--loyalty-refund-flow .label { fill: #302F37; font: 600 13px 'Poppins', system-ui, -apple-system, sans-serif; }
      .ottu-dgm--loyalty-refund-flow .label-white { fill: #FFFFFF; font: 600 13px 'Poppins', system-ui, -apple-system, sans-serif; }
      .ottu-dgm--loyalty-refund-flow .sub { fill: #6B6B72; font: 400 11px 'Poppins', system-ui, -apple-system, sans-serif; }
      .ottu-dgm--loyalty-refund-flow .sub-white { fill: #FFFFFF; font: 400 11px 'Poppins', system-ui, -apple-system, sans-serif; opacity: 0.9; }
      .ottu-dgm--loyalty-refund-flow .divider { stroke: #E0E0E3; stroke-width: 1; }
      .ottu-dgm--loyalty-refund-flow .arrow { fill: none; stroke: #8B8A90; stroke-width: 1.4; }
      .ottu-dgm--loyalty-refund-flow .arrow-head { fill: #8B8A90; }
      .ottu-dgm--loyalty-refund-flow .arrow-label { fill: #6B6B72; font: 500 10px 'Poppins', system-ui, -apple-system, sans-serif; letter-spacing: 0.3px; }
      .ottu-dgm--loyalty-refund-flow .arrow-label-bg { fill: #FFFFFF; }
    

      /* dark theme — overrides only what changes */
      [data-theme='dark'] .ottu-dgm--loyalty-refund-flow .node { fill: #171A21; stroke: #1E2939; }
      [data-theme='dark'] .ottu-dgm--loyalty-refund-flow .container-bg { fill: #0F1A22; }
      [data-theme='dark'] .ottu-dgm--loyalty-refund-flow .platform-label { fill: #5CB4E1; }
      [data-theme='dark'] .ottu-dgm--loyalty-refund-flow .label { fill: #E5E7EB; }
      [data-theme='dark'] .ottu-dgm--loyalty-refund-flow .sub { fill: #A0A0A8; }
      [data-theme='dark'] .ottu-dgm--loyalty-refund-flow .divider { stroke: #1E2939; }
      [data-theme='dark'] .ottu-dgm--loyalty-refund-flow .arrow { stroke: #8A8A92; }
      [data-theme='dark'] .ottu-dgm--loyalty-refund-flow .arrow-head { fill: #8A8A92; }
      [data-theme='dark'] .ottu-dgm--loyalty-refund-flow .arrow-label { fill: #A0A0A8; }
      [data-theme='dark'] .ottu-dgm--loyalty-refund-flow .arrow-label-bg { fill: #0F1A22; }
    </style>
  </defs>
  <rect class="node" x="30" y="24" width="180" height="52" rx="8" />
  <text class="label" x="120" y="47" text-anchor="middle">Merchant</text>
  <text class="sub" x="120" y="65" text-anchor="middle">Dashboard or API</text>
  <line class="divider" x1="120" y1="76" x2="120" y2="570" stroke-dasharray="3 4" />
  <rect class="accent" x="270" y="24" width="180" height="52" rx="8" />
  <text class="label-white" x="360" y="47" text-anchor="middle">Ottu</text>
  <text class="sub-white" x="360" y="65" text-anchor="middle">Refund handling</text>
  <line class="divider" x1="360" y1="76" x2="360" y2="570" stroke-dasharray="3 4" />
  <rect class="node" x="510" y="24" width="180" height="52" rx="8" />
  <text class="label" x="600" y="47" text-anchor="middle">Payment gateway</text>
  <text class="sub" x="600" y="65" text-anchor="middle">Card portion</text>
  <line class="divider" x1="600" y1="76" x2="600" y2="570" stroke-dasharray="3 4" />
  <rect class="node" x="750" y="24" width="180" height="52" rx="8" />
  <text class="label" x="840" y="47" text-anchor="middle">STC Qitaf</text>
  <text class="sub" x="840" y="65" text-anchor="middle">Loyalty provider</text>
  <line class="divider" x1="840" y1="76" x2="840" y2="570" stroke-dasharray="3 4" />
  <path class="arrow" d="M 124 130 L 356 130" marker-end="url(#arrow-loyalty-refund-flow)" />
  <rect class="arrow-label-bg" x="162" y="111" width="157" height="16" rx="3" />
  <text class="arrow-label" x="240" y="122" text-anchor="middle">1 Refund gateway portion</text>
  <path class="arrow" d="M 364 180 L 596 180" marker-end="url(#arrow-loyalty-refund-flow)" />
  <rect class="arrow-label-bg" x="428" y="161" width="104" height="16" rx="3" />
  <text class="arrow-label" x="480" y="172" text-anchor="middle">2 Refund 70 SAR</text>
  <path class="arrow" d="M 596 225 L 364 225" stroke-dasharray="4 3" marker-end="url(#arrow-loyalty-refund-flow)" />
  <rect class="arrow-label-bg" x="443" y="206" width="75" height="16" rx="3" />
  <text class="arrow-label" x="480" y="217" text-anchor="middle">3 Refunded</text>
  <rect class="node" x="230" y="246" width="260" height="30" rx="6" />
  <text class="sub" x="360" y="265" text-anchor="middle">Nothing left owed through the gateway</text>
  <path class="arrow" d="M 364 320 L 836 320" marker-end="url(#arrow-loyalty-refund-flow)" />
  <rect class="arrow-label-bg" x="492" y="301" width="216" height="16" rx="3" />
  <text class="arrow-label" x="600" y="312" text-anchor="middle">4 Reverse redeemed points (30 SAR)</text>
  <path class="arrow" d="M 836 365 L 364 365" stroke-dasharray="4 3" marker-end="url(#arrow-loyalty-refund-flow)" />
  <rect class="arrow-label-bg" x="563" y="346" width="75" height="16" rx="3" />
  <text class="arrow-label" x="600" y="357" text-anchor="middle">5 Reversed</text>
  <path class="arrow" d="M 356 415 L 124 415" stroke-dasharray="4 3" marker-end="url(#arrow-loyalty-refund-flow)" />
  <rect class="arrow-label-bg" x="144" y="396" width="193" height="16" rx="3" />
  <text class="arrow-label" x="240" y="407" text-anchor="middle">6 Response: both records exist</text>
  <path class="arrow" d="M 356 460 L 124 460" stroke-dasharray="4 3" marker-end="url(#arrow-loyalty-refund-flow)" />
  <rect class="arrow-label-bg" x="135" y="441" width="210" height="16" rx="3" />
  <text class="arrow-label" x="240" y="452" text-anchor="middle">7 Webhook: points return (30 SAR)</text>
  <path class="arrow" d="M 356 505 L 124 505" stroke-dasharray="4 3" marker-end="url(#arrow-loyalty-refund-flow)" />
  <rect class="arrow-label-bg" x="132" y="486" width="216" height="16" rx="3" />
  <text class="arrow-label" x="240" y="497" text-anchor="middle">8 Webhook: gateway refund (70 SAR)</text>
  <path class="arrow" d="M 364 550 L 836 550" marker-end="url(#arrow-loyalty-refund-flow)" />
  <rect class="arrow-label-bg" x="516" y="531" width="169" height="16" rx="3" />
  <text class="arrow-label" x="600" y="542" text-anchor="middle">9 Reduce the earned reward</text>
</svg>`;

export default function LoyaltyRefundDiagram(): React.JSX.Element {
  return (
    <Diagram
      svg={SVG}
      alt="Refunding a split order: Ottu refunds the gateway portion, then reverses the redeemed points at STC Qitaf, answers the merchant with both records booked, sends the points-return webhook before the gateway-refund webhook, and reduces the earned reward."
    />
  );
}
