import React from "react";
import Diagram from "@site/src/components/Diagram";

/**
 * Auto-debit MIT charge: two-step vs One-Step Checkout.
 *
 * Single inline, theme-aware SVG generated by the `svg-diagram` skill
 * (scripts/inline-svg.py, slug "auto-debit-one-step"). Scoped `<style>` with
 * light rules + `[data-theme='dark']` overrides; renders in true Poppins and
 * switches with the page theme. To change it, edit the source SVG and re-run
 * inline-svg.py.
 *
 * The point of the diagram: for a merchant-initiated charge on a saved token,
 * the two-step path is Checkout API (create session) -> Auto-Debit API (charge),
 * while One-Step Checkout collapses both into a SINGLE Checkout API call that
 * carries the token in `payment_instrument` and returns the result directly.
 * The one-step Checkout API node is the only accent node (the thing to notice).
 */
const SVG = String.raw`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 980 320"
     role="img" aria-labelledby="diagram-title-auto-debit-one-step diagram-desc-auto-debit-one-step" preserveAspectRatio="xMidYMid meet" class="ottu-dgm--auto-debit-one-step">
  <title id="diagram-title-auto-debit-one-step">Auto-Debit MIT: two-step versus One-Step Checkout</title>
  <desc id="diagram-desc-auto-debit-one-step">Two ways to charge a saved token for a merchant-initiated auto-debit payment. In the two-step path the merchant backend first calls the Checkout API to create a session, then calls the Auto-Debit (Native Payments) API to charge the saved token, and the payment result is returned in the API response. In the one-step path the merchant backend makes a single Checkout API call with the saved token in payment_instrument, and Ottu creates the session and charges the token in one call, returning the payment result directly.</desc>

  <defs>
    <marker id="arrow-auto-debit-one-step" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto">
      <path class="arrow-head" d="M0,1 L9,5 L0,9 z" />
    </marker>
    <style>
      .ottu-dgm--auto-debit-one-step .node { fill: #FFFFFF; stroke: #D4D4D4; stroke-width: 1.4; }
      .ottu-dgm--auto-debit-one-step .accent { fill: #0B82BE; stroke: #0B82BE; stroke-width: 1.4; }
      .ottu-dgm--auto-debit-one-step .danger { fill: #ED2833; stroke: #ED2833; stroke-width: 1.4; }
      .ottu-dgm--auto-debit-one-step .container-bg { fill: #F6FAFD; stroke: #0B82BE; stroke-dasharray: 5 5; stroke-width: 1.2; opacity: 0.85; }
      .ottu-dgm--auto-debit-one-step .platform-label { fill: #0B82BE; font: 700 10px 'Poppins', system-ui, -apple-system, sans-serif; letter-spacing: 1.6px; }
      .ottu-dgm--auto-debit-one-step .label { fill: #302F37; font: 600 13px 'Poppins', system-ui, -apple-system, sans-serif; }
      .ottu-dgm--auto-debit-one-step .label-white { fill: #FFFFFF; font: 600 13px 'Poppins', system-ui, -apple-system, sans-serif; }
      .ottu-dgm--auto-debit-one-step .sub { fill: #6B6B72; font: 400 11px 'Poppins', system-ui, -apple-system, sans-serif; }
      .ottu-dgm--auto-debit-one-step .sub-white { fill: #FFFFFF; font: 400 11px 'Poppins', system-ui, -apple-system, sans-serif; opacity: 0.9; }
      .ottu-dgm--auto-debit-one-step .divider { stroke: #E0E0E3; stroke-width: 1; }
      .ottu-dgm--auto-debit-one-step .arrow { fill: none; stroke: #8B8A90; stroke-width: 1.4; }
      .ottu-dgm--auto-debit-one-step .arrow-head { fill: #8B8A90; }
      .ottu-dgm--auto-debit-one-step .arrow-label { fill: #6B6B72; font: 500 10px 'Poppins', system-ui, -apple-system, sans-serif; letter-spacing: 0.3px; }
      .ottu-dgm--auto-debit-one-step .arrow-label-bg { fill: #F6FAFD; }


      /* dark theme — overrides only what changes */
      [data-theme='dark'] .ottu-dgm--auto-debit-one-step .node { fill: #171A21; stroke: #1E2939; }
      [data-theme='dark'] .ottu-dgm--auto-debit-one-step .container-bg { fill: #0F1A22; }
      [data-theme='dark'] .ottu-dgm--auto-debit-one-step .platform-label { fill: #5CB4E1; }
      [data-theme='dark'] .ottu-dgm--auto-debit-one-step .label { fill: #E5E7EB; }
      [data-theme='dark'] .ottu-dgm--auto-debit-one-step .sub { fill: #A0A0A8; }
      [data-theme='dark'] .ottu-dgm--auto-debit-one-step .divider { stroke: #1E2939; }
      [data-theme='dark'] .ottu-dgm--auto-debit-one-step .arrow { stroke: #8A8A92; }
      [data-theme='dark'] .ottu-dgm--auto-debit-one-step .arrow-head { fill: #8A8A92; }
      [data-theme='dark'] .ottu-dgm--auto-debit-one-step .arrow-label { fill: #A0A0A8; }
      [data-theme='dark'] .ottu-dgm--auto-debit-one-step .arrow-label-bg { fill: #0F1A22; }
    </style>
  </defs>

  <!-- ===== TWO-STEP lane ===== -->
  <text class="platform-label" x="24" y="40">TWO-STEP · TWO API CALLS</text>

  <rect class="node" x="24" y="62" width="156" height="62" rx="8" />
  <text class="label" x="102" y="89" text-anchor="middle">Merchant Backend</text>
  <text class="sub" x="102" y="108" text-anchor="middle">Your server</text>

  <rect class="node" x="300" y="62" width="156" height="62" rx="8" />
  <text class="label" x="378" y="89" text-anchor="middle">Checkout API</text>
  <text class="sub" x="378" y="108" text-anchor="middle">Create session</text>

  <rect class="node" x="560" y="62" width="166" height="62" rx="8" />
  <text class="label" x="643" y="89" text-anchor="middle">Auto-Debit API</text>
  <text class="sub" x="643" y="108" text-anchor="middle">Charge saved token</text>

  <rect class="node" x="820" y="62" width="140" height="62" rx="8" />
  <text class="label" x="890" y="89" text-anchor="middle">Payment result</text>
  <text class="sub" x="890" y="108" text-anchor="middle">state = paid</text>

  <path class="arrow" d="M 180 93 L 300 93" marker-end="url(#arrow-auto-debit-one-step)" />
  <rect class="arrow-label-bg" x="184" y="85" width="112" height="15" rx="3" />
  <text class="arrow-label" x="240" y="96" text-anchor="middle">1 · create session</text>

  <path class="arrow" d="M 456 93 L 560 93" marker-end="url(#arrow-auto-debit-one-step)" />
  <rect class="arrow-label-bg" x="459" y="85" width="98" height="15" rx="3" />
  <text class="arrow-label" x="508" y="96" text-anchor="middle">2 · charge token</text>

  <path class="arrow" d="M 726 93 L 820 93" marker-end="url(#arrow-auto-debit-one-step)" />
  <rect class="arrow-label-bg" x="749" y="85" width="48" height="15" rx="3" />
  <text class="arrow-label" x="773" y="96" text-anchor="middle">result</text>

  <!-- ===== ONE-STEP lane ===== -->
  <text class="platform-label" x="24" y="212">ONE-STEP · ONE API CALL</text>

  <rect class="node" x="24" y="234" width="156" height="62" rx="8" />
  <text class="label" x="102" y="261" text-anchor="middle">Merchant Backend</text>
  <text class="sub" x="102" y="280" text-anchor="middle">Your server</text>

  <rect class="accent" x="300" y="234" width="240" height="62" rx="8" />
  <text class="label-white" x="420" y="261" text-anchor="middle">Checkout API</text>
  <text class="sub-white" x="420" y="280" text-anchor="middle">token in payment_instrument</text>

  <rect class="node" x="620" y="234" width="150" height="62" rx="8" />
  <text class="label" x="695" y="261" text-anchor="middle">Payment result</text>
  <text class="sub" x="695" y="280" text-anchor="middle">state = paid</text>

  <path class="arrow" d="M 180 265 L 300 265" marker-end="url(#arrow-auto-debit-one-step)" />
  <rect class="arrow-label-bg" x="206" y="257" width="68" height="15" rx="3" />
  <text class="arrow-label" x="240" y="268" text-anchor="middle">single call</text>

  <path class="arrow" d="M 540 265 L 620 265" marker-end="url(#arrow-auto-debit-one-step)" />
  <rect class="arrow-label-bg" x="542" y="257" width="76" height="15" rx="3" />
  <text class="arrow-label" x="580" y="268" text-anchor="middle">direct result</text>
</svg>`;

export default function OneStepMITFlow(): React.JSX.Element {
  return (
    <Diagram
      svg={SVG}
      alt="Auto-debit MIT charge, two ways. Two-step: the merchant backend calls the Checkout API to create a session, then calls the Auto-Debit (Native Payments) API to charge the saved token, returning the payment result. One-step: the merchant backend makes a single Checkout API call with the saved token in payment_instrument, and Ottu creates the session and charges the token in one call, returning the payment result directly."
    />
  );
}
