import React from "react";
import Diagram from "@site/src/components/Diagram";

/**
 * Recurring payments (auto-debit) flow: CIT setup vs MIT charge.
 *
 * Single inline, theme-aware SVG generated by the `svg-diagram` skill
 * (scripts/inline-svg.py, slug "recurring-flow"). Scoped `<style>` with light
 * rules + `[data-theme='dark']` overrides; renders in true Poppins and switches
 * with the page theme. To change it, edit the source SVG and re-run inline-svg.py.
 *
 * Accuracy notes (per the page's Step-by-Step):
 *  - The CUSTOMER never calls an Ottu API. The merchant calls the Checkout API
 *    (sessions only), gets session_id + checkout_url, and redirects the customer
 *    to the checkout page (Ottu-hosted OR a self-hosted SDK embed — hence it
 *    sits OUTSIDE the Ottu Platform box). The card is entered there.
 *  - The checkout page submits the payment to OTTU (not the Checkout API). Ottu
 *    processes it and sends the merchant an ASYNC webhook carrying the token
 *    (CIT only).
 *  - The MIT charge (two-step: Checkout API session -> Native Payments API)
 *    returns the result DIRECTLY in the API response — there is NO MIT webhook.
 */
const SVG = String.raw`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 880 530"
     role="img" aria-labelledby="rec-title-recurring-flow rec-desc-recurring-flow" preserveAspectRatio="xMidYMid meet" class="ottu-dgm--recurring-flow">
  <title id="rec-title-recurring-flow">Recurring Payments: CIT setup and MIT auto-debit</title>
  <desc id="rec-desc-recurring-flow">In the cardholder-initiated setup (CIT), the merchant backend creates a session via the Checkout API and redirects the customer to the checkout page (Ottu-hosted or a self-hosted SDK embed), where the customer enters and saves their card and pays. The payment is submitted to Ottu, which processes it and then sends the merchant backend an asynchronous webhook notification carrying the saved-card token. For each merchant-initiated charge (MIT), the merchant creates a session via the Checkout API and calls the Native Payments API with the saved token; the payment result is returned directly in the API response — there is no webhook for MIT charges.</desc>

  <defs>
    <marker id="arrow-recurring-flow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto">
      <path class="arrow-head" d="M0,1 L9,5 L0,9 z" />
    </marker>
    <style>
      .ottu-dgm--recurring-flow .node { fill: #FFFFFF; stroke: #D4D4D4; stroke-width: 1.4; }
      .ottu-dgm--recurring-flow .accent { fill: #0B82BE; stroke: #0B82BE; stroke-width: 1.4; }
      .ottu-dgm--recurring-flow .danger { fill: #ED2833; stroke: #ED2833; stroke-width: 1.4; }
      .ottu-dgm--recurring-flow .container-bg { fill: #F6FAFD; stroke: #0B82BE; stroke-dasharray: 5 5; stroke-width: 1.2; opacity: 0.85; }
      .ottu-dgm--recurring-flow .platform-label { fill: #0B82BE; font: 700 10px 'Poppins', system-ui, -apple-system, sans-serif; letter-spacing: 1.6px; }
      .ottu-dgm--recurring-flow .label { fill: #302F37; font: 600 13px 'Poppins', system-ui, -apple-system, sans-serif; }
      .ottu-dgm--recurring-flow .label-white { fill: #FFFFFF; font: 600 13px 'Poppins', system-ui, -apple-system, sans-serif; }
      .ottu-dgm--recurring-flow .sub { fill: #6B6B72; font: 400 11px 'Poppins', system-ui, -apple-system, sans-serif; }
      .ottu-dgm--recurring-flow .sub-white { fill: #FFFFFF; font: 400 11px 'Poppins', system-ui, -apple-system, sans-serif; opacity: 0.9; }
      .ottu-dgm--recurring-flow .arrow { fill: none; stroke: #8B8A90; stroke-width: 1.4; }
      .ottu-dgm--recurring-flow .arrow-head { fill: #8B8A90; }
      .ottu-dgm--recurring-flow .arrow-label { fill: #6B6B72; font: 500 10px 'Poppins', system-ui, -apple-system, sans-serif; letter-spacing: 0.3px; }
      .ottu-dgm--recurring-flow .arrow-label-bg { fill: #F6FAFD; }

      /* dark theme — overrides only what changes */
      [data-theme='dark'] .ottu-dgm--recurring-flow .node { fill: #171A21; stroke: #1E2939; }
      [data-theme='dark'] .ottu-dgm--recurring-flow .container-bg { fill: #0F1A22; }
      [data-theme='dark'] .ottu-dgm--recurring-flow .platform-label { fill: #5CB4E1; }
      [data-theme='dark'] .ottu-dgm--recurring-flow .label { fill: #E5E7EB; }
      [data-theme='dark'] .ottu-dgm--recurring-flow .sub { fill: #A0A0A8; }
      [data-theme='dark'] .ottu-dgm--recurring-flow .arrow { stroke: #8A8A92; }
      [data-theme='dark'] .ottu-dgm--recurring-flow .arrow-head { fill: #8A8A92; }
      [data-theme='dark'] .ottu-dgm--recurring-flow .arrow-label { fill: #A0A0A8; }
      [data-theme='dark'] .ottu-dgm--recurring-flow .arrow-label-bg { fill: #0F1A22; }
    </style>
  </defs>

  <!-- Phase band labels -->
  <text class="platform-label" x="30" y="58">CIT · CUSTOMER PRESENT</text>
  <text class="platform-label" x="30" y="426">MIT · NO CUSTOMER</text>

  <!-- Ottu Platform container (Checkout Page is intentionally OUTSIDE it) -->
  <rect class="container-bg" x="288" y="112" width="566" height="406" rx="14" />
  <text class="platform-label" x="308" y="138">OTTU PLATFORM</text>

  <!-- Checkout Page (OUTSIDE platform: Ottu-hosted or self-hosted SDK embed) -->
  <rect class="node" x="566" y="30" width="206" height="60" rx="8" />
  <text class="label" x="669" y="56" text-anchor="middle">Checkout Page</text>
  <text class="sub" x="669" y="75" text-anchor="middle">Ottu or self-hosted</text>

  <!-- Customer (CIT only) -->
  <rect class="node" x="30" y="156" width="170" height="46" rx="23" />
  <text class="label" x="115" y="184" text-anchor="middle">Customer</text>

  <!-- Merchant Backend (orchestrator) -->
  <rect class="node" x="30" y="288" width="170" height="78" rx="8" />
  <text class="label" x="115" y="320" text-anchor="middle">Merchant Backend</text>
  <text class="sub" x="115" y="340" text-anchor="middle">Your server</text>

  <!-- Checkout API (sessions only) -->
  <rect class="node" x="330" y="162" width="232" height="74" rx="8" />
  <text class="label" x="446" y="192" text-anchor="middle">Checkout API</text>
  <text class="sub" x="446" y="212" text-anchor="middle">Creates CIT &amp; MIT sessions</text>

  <!-- Ottu (processes the payment + sends the webhook) -->
  <rect class="node" x="606" y="162" width="208" height="74" rx="8" />
  <text class="label" x="710" y="192" text-anchor="middle">Ottu</text>
  <text class="sub" x="710" y="212" text-anchor="middle">Processes payment · webhooks</text>

  <!-- Native Payments API (MIT charge, accent) -->
  <rect class="accent" x="452" y="420" width="244" height="74" rx="8" />
  <text class="label-white" x="574" y="450" text-anchor="middle">Native Payments API</text>
  <text class="sub-white" x="574" y="470" text-anchor="middle">Charge saved token</text>

  <!-- ===== CIT arrows ===== -->
  <!-- Merchant Backend -> Checkout API (create session, shared CIT + MIT) -->
  <path class="arrow" d="M 200 300 C 270 292 290 224 330 210" marker-end="url(#arrow-recurring-flow)" />
  <rect class="arrow-label-bg" x="236" y="248" width="92" height="15" rx="3" />
  <text class="arrow-label" x="282" y="259" text-anchor="middle">create session</text>

  <!-- Merchant Backend -> Customer (redirect to checkout) -->
  <path class="arrow" d="M 115 288 L 115 204" marker-end="url(#arrow-recurring-flow)" />
  <rect class="arrow-label-bg" x="51" y="237" width="128" height="15" rx="3" />
  <text class="arrow-label" x="115" y="248" text-anchor="middle">redirect to checkout</text>

  <!-- Customer -> Checkout Page (enters card; customer touches the UI, never the API) -->
  <path class="arrow" d="M 200 168 C 360 86 480 68 566 66" marker-end="url(#arrow-recurring-flow)" />
  <rect class="arrow-label-bg" x="328" y="82" width="106" height="15" rx="3" />
  <text class="arrow-label" x="381" y="93" text-anchor="middle">enters card · pays</text>

  <!-- Checkout Page -> Ottu (payment submitted to Ottu, NOT the Checkout API) -->
  <path class="arrow" d="M 686 90 C 694 112 700 136 704 162" marker-end="url(#arrow-recurring-flow)" />
  <rect class="arrow-label-bg" x="658" y="120" width="92" height="15" rx="3" />
  <text class="arrow-label" x="704" y="131" text-anchor="middle">submit payment</text>

  <!-- Ottu -> Merchant Backend (Ottu sends the async webhook with the token) -->
  <path class="arrow" d="M 606 222 C 440 288 360 332 200 330" stroke-dasharray="4 3" marker-end="url(#arrow-recurring-flow)" />
  <rect class="arrow-label-bg" x="356" y="312" width="166" height="15" rx="3" />
  <text class="arrow-label" x="439" y="323" text-anchor="middle">Ottu webhook · token (async)</text>

  <!-- ===== MIT arrows ===== -->
  <!-- Checkout API -> Native Payments API (the MIT session_id feeds the charge: two-step) -->
  <path class="arrow" d="M 470 236 C 500 320 540 380 566 420" stroke-dasharray="1 3" marker-end="url(#arrow-recurring-flow)" />
  <rect class="arrow-label-bg" x="486" y="348" width="96" height="15" rx="3" />
  <text class="arrow-label" x="534" y="359" text-anchor="middle">session_id (MIT)</text>

  <!-- Merchant Backend -> Native Payments API (charge saved token) -->
  <path class="arrow" d="M 200 352 C 300 414 360 452 452 460" marker-end="url(#arrow-recurring-flow)" />
  <rect class="arrow-label-bg" x="226" y="408" width="152" height="15" rx="3" />
  <text class="arrow-label" x="302" y="419" text-anchor="middle">charge saved token · MIT</text>

  <!-- Native Payments API -> Merchant Backend (direct result, NOT a webhook) -->
  <path class="arrow" d="M 452 482 Q 300 524 200 372" marker-end="url(#arrow-recurring-flow)" />
  <rect class="arrow-label-bg" x="228" y="502" width="128" height="15" rx="3" />
  <text class="arrow-label" x="292" y="513" text-anchor="middle">payment result (direct)</text>
</svg>`;

export default function RecurringFlow(): React.JSX.Element {
  return (
    <Diagram
      svg={SVG}
      alt="Recurring payments flow. CIT setup (customer present): the merchant backend creates a session via the Checkout API and redirects the customer to the checkout page (Ottu-hosted or a self-hosted SDK embed); the customer enters and saves their card and pays; the payment is submitted to Ottu, which processes it and sends the merchant an asynchronous webhook notification with the saved-card token. MIT charge (no customer): the merchant creates a session via the Checkout API and calls the Native Payments API with the saved token, and the payment result is returned directly in the response — no webhook."
    />
  );
}
